<a href="https://colab.research.google.com/github/ylmgrbzz/Turkey-Car-Market-Analysis/blob/main/Turkey_Car_Market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import random

In [2]:
car=pd.read_csv("car.csv")

In [3]:
car.head(3)

,İlan Tarihi,Marka,Arac Tip Grubu,Arac Tip,Model Yıl,Yakıt Turu,Vites,CCM,Beygir Gucu,Renk,Kasa Tipi,Kimden,Durum,Km,Fiyat
0,27/05/2020,Jaguar,XF,2.0 D Prestige Plus,2017.0,Dizel,Otomatik Vites,1801-2000 cc,176-200 BG,Lacivert,Hatchback 5 Kapı,Galeriden,2. El,26100,634500
1,16/06/2020,Acura,CL,-,2015.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,101-125 BG,Mavi,Sedan,Sahibinden,2. El,127000,151500
2,14/06/2020,Acura,CL,2.2,1994.0,Benzin/LPG,Düz Vites,1301-1600 cc,101-125 BG,Turkuaz,Sedan,Sahibinden,2. El,175000,19750

In [12]:
car.info

<bound method DataFrame.info of      İlan Tarihi   Marka Arac Tip Grubu             Arac Tip  Model Yıl  \
0     27/05/2020  Jaguar             XF  2.0 D Prestige Plus     2017.0
1     16/06/2020   Acura             CL                    -     2015.0
2     14/06/2020   Acura             CL                  2.2     1994.0
3     11/06/2020   Acura             CL                    -     2013.0
4     11/06/2020   Acura             CL                  2.2     2010.0
...          ...     ...            ...                  ...        ...
9039  06/06/2020   Tofaş          Şahin                  1.6     1994.0
9040  05/06/2020   Tofaş          Şahin        Şahin 5 vites     1992.0
9041  05/06/2020   Tofaş          Doğan                  SLX     1993.0
9042  04/06/2020   Tofaş         Kartal       Kartal 5 Vites     1991.0
9043  04/06/2020   Tofaş         Kartal       Kartal 5 Vites     1996.0

      Yakıt Turu                Vites           CCM Beygir Gucu         Renk  \
0          Dizel       Otomatik Vites  1801-2000 cc  176-200 BG    Lacivert
1          Dizel  Yarı Otomatik Vites  1301-1600 cc  101-125 BG        Mavi
2     Benzin/LPG            Düz Vites  1301-1600 cc  101-125 BG     Turkuaz
3          Dizel            Düz Vites  1301-1600 cc   76-100 BG  Kahverengi
4          Dizel       Otomatik Vites  1801-2000 cc  151-175 BG       Beyaz
...          ...                  ...           ...         ...          ...
9039  Benzin/LPG            Düz Vites  1301-1600 cc    51-75 BG       Beyaz
9040  Benzin/LPG            Düz Vites  1301-1600 cc   76-100 BG         Bej
9041  Benzin/LPG            Düz Vites  1301-1600 cc   76-100 BG       Yeşil
9042  Benzin/LPG            Düz Vites  1601-1800 cc   76-100 BG     Kırmızı
9043  Benzin/LPG            Düz Vites  1301-1600 cc    51-75 BG       Beyaz

             Kasa Tipi      Kimden  Durum      Km   Fiyat
0     Hatchback 5 Kapı   Galeriden  2. El   26100  634500
1                Sedan  Sahibinden  2. El  127000  151500
2                Sedan  Sahibinden  2. El  175000   19750
3                Sedan  Sahibinden  2. El     325   52000
4                Sedan  Sahibinden  2. El  207000  148750
...                ...         ...    ...     ...     ...
9039             Sedan   Galeriden  2. El  121212   12250
9040             Sedan  Sahibinden  2. El   54000   16300
9041             Sedan  Sahibinden  2. El  135000   19000
9042  Hatchback 5 Kapı   Galeriden  2. El  250000   11000
9043             Sedan   Galeriden  2. El      11   15750

[9044 rows x 15 columns]>

In [4]:
car["Marka"]

0       Jaguar
1        Acura
2        Acura
3        Acura
4        Acura
         ...
9039     Tofaş
9040     Tofaş
9041     Tofaş
9042     Tofaş
9043     Tofaş
Name: Marka, Length: 9044, dtype: object

In [5]:
car["Marka"].value_counts()

Renault       2079
Fiat           654
Opel           647
Hyundai        639
BMW            616
Mercedes       613
Ford           602
Audi           430
Peugeot        421
Dacia          323
Honda          263
Skoda          259
Nissan         229
Citroen        199
Land Rover     182
Kia            166
Seat           151
Chevrolet      127
Jeep            91
Porsche         56
Tofaş           45
Acura           42
Mitsubishi      32
Mini            31
Jaguar          30
Mazda           24
Volkswagen      18
Alfa Romeo      17
Lada            16
Chrysler        13
Infiniti        10
Isuzu            9
Rover            4
Maserati         3
Geely            2
Chery            1
Name: Marka, dtype: int64

In [6]:
car["Arac Tip Grubu"].value_counts()

Clio       490
Megane     443
Fluence    426
Symbol     420
Focus      359
          ...
Omega        1
Mustang      1
Cascada      1
Mokka X      1
Country      1
Name: Arac Tip Grubu, Length: 387, dtype: int64

In [7]:
car["Fiyat"].mean()

148069.6386554622

In [8]:
marka=car["Marka"]=="Renault"
model=car["Arac Tip Grubu"]=="Megane"

In [10]:
car[marka& model]["Fiyat"].mean()

105790.06320541761

In [9]:
car[marka& model]

,İlan Tarihi,Marka,Arac Tip Grubu,Arac Tip,Model Yıl,Yakıt Turu,Vites,CCM,Beygir Gucu,Renk,Kasa Tipi,Kimden,Durum,Km,Fiyat
6405,16/06/2020,Renault,Megane,1.6 Alize,1998.0,Benzin/LPG,Düz Vites,1301-1600 cc,100 BG ve altı,Mavi,Sedan,Galeriden,2. El,200000,27500
6407,16/06/2020,Renault,Megane,1.6 CC Dynamique,2005.0,Benzin/LPG,Düz Vites,1301-1600 cc,101-125 BG,Gri,Sedan,Galeriden,2. El,218000,39500
6419,15/06/2020,Renault,Megane,1.6 Dynamique,2004.0,Benzin/LPG,Düz Vites,Bilmiyorum,Bilmiyorum,Gri,Sedan,Sahibinden,2. El,174000,64000
6427,15/06/2020,Renault,Megane,2.0\n,1998.0,Benzin/LPG,Düz Vites,1801-2000 cc,101-125 BG,Gri,Sedan,Galeriden,2. El,280000,30000
6450,14/06/2020,Renault,Megane,1.6 Expression,2003.0,Benzin,Düz Vites,1301-1600 cc,101-125 BG,Yeşil,Sedan,Galeriden,2. El,95000,51500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8540,18/04/2020,Renault,Megane,1.5 dCi Touch,2017.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,Bilmiyorum,Beyaz,Sedan,Galeriden,2. El,88000,149000
8545,18/04/2020,Renault,Megane,1.5 dCi Touch,2017.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,Bilmiyorum,Beyaz,Sedan,Galeriden,2. El,74000,134750
8550,18/04/2020,Renault,Megane,Diğer,2009.0,Dizel,Düz Vites,1301-1600 cc,Bilmiyorum,Gümüş Gri,Sedan,Galeriden,2. El,210000,44750
8553,18/04/2020,Renault,Megane,1.5 dCi Touch,2017.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,Bilmiyorum,Beyaz,Sedan,Galeriden,2. El,88000,149000
8558,18/04/2020,Renault,Megane,1.5 dCi Touch,2017.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,Bilmiyorum,Beyaz,Sedan,Galeriden,2. El,74000,134750

In [ ]:
marka=car["Marka"]=="Mitsubishi"
model=car["Arac Tip Grubu"]=="Lancer"

In [ ]:
car[marka& model]

,İlan Tarihi,Marka,Arac Tip Grubu,Arac Tip,Model Yıl,Yakıt Turu,Vites,CCM,Beygir Gucu,Renk,Kasa Tipi,Kimden,Durum,Km,Fiyat
4960,09/06/2020,Mitsubishi,Lancer,1.6 Invite Otm,2006.0,Benzin/LPG,Otomatik Vites,1301-1600 cc,100 BG ve altı,Gümüş Gri,Sedan,Sahibinden,2. El,135000,55000
4961,09/06/2020,Mitsubishi,Lancer,1.6 Invite,2013.0,Benzin/LPG,Düz Vites,1301-1600 cc,Bilmiyorum,Beyaz,Sedan,Galeriden,2. El,238000,79750
4988,03/04/2020,Mitsubishi,Lancer,1.6 Invite,2006.0,Benzin/LPG,Düz Vites,1301-1600 cc,100 BG ve altı,Lacivert,Sedan,Sahibinden,2. El,206000,57500

In [ ]:
car["Marka"].unique()

array(['Jaguar', 'Acura', 'Jeep', 'Hyundai', 'Alfa Romeo', 'Audi',
       'Mercedes', 'Volkswagen', 'Land Rover', 'BMW', 'Dacia', 'Renault',
       'Peugeot', 'Chevrolet', 'Chery', 'Citroen', 'Chrysler', 'Fiat',
       'Ford', 'Honda', 'Geely', 'Infiniti', 'Isuzu', 'Kia', 'Lada',
       'Maserati', 'Mazda', 'Mini', 'Mitsubishi', 'Nissan', 'Opel',
       'Porsche', 'Rover', 'Seat', 'Skoda', 'Tofaş'], dtype=object)

In [13]:
car["İlan Tarihi"].astype("datetime64")

0      2020-05-27
1      2020-06-16
2      2020-06-14
3      2020-11-06
4      2020-11-06
          ...
9039   2020-06-06
9040   2020-05-06
9041   2020-05-06
9042   2020-04-06
9043   2020-04-06
Name: İlan Tarihi, Length: 9044, dtype: datetime64[ns]

In [14]:
pd.to_datetime(car["İlan Tarihi"])

0      2020-05-27
1      2020-06-16
2      2020-06-14
3      2020-11-06
4      2020-11-06
          ...
9039   2020-06-06
9040   2020-05-06
9041   2020-05-06
9042   2020-04-06
9043   2020-04-06
Name: İlan Tarihi, Length: 9044, dtype: datetime64[ns]

In [15]:
car["İlan Tarihi"]=pd.to_datetime(car["İlan Tarihi"]) 
car

,İlan Tarihi,Marka,Arac Tip Grubu,Arac Tip,Model Yıl,Yakıt Turu,Vites,CCM,Beygir Gucu,Renk,Kasa Tipi,Kimden,Durum,Km,Fiyat
0,2020-05-27,Jaguar,XF,2.0 D Prestige Plus,2017.0,Dizel,Otomatik Vites,1801-2000 cc,176-200 BG,Lacivert,Hatchback 5 Kapı,Galeriden,2. El,26100,634500
1,2020-06-16,Acura,CL,-,2015.0,Dizel,Yarı Otomatik Vites,1301-1600 cc,101-125 BG,Mavi,Sedan,Sahibinden,2. El,127000,151500
2,2020-06-14,Acura,CL,2.2,1994.0,Benzin/LPG,Düz Vites,1301-1600 cc,101-125 BG,Turkuaz,Sedan,Sahibinden,2. El,175000,19750
3,2020-11-06,Acura,CL,-,2013.0,Dizel,Düz Vites,1301-1600 cc,76-100 BG,Kahverengi,Sedan,Sahibinden,2. El,325,52000
4,2020-11-06,Acura,CL,2.2,2010.0,Dizel,Otomatik Vites,1801-2000 cc,151-175 BG,Beyaz,Sedan,Sahibinden,2. El,207000,148750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9039,2020-06-06,Tofaş,Şahin,1.6,1994.0,Benzin/LPG,Düz Vites,1301-1600 cc,51-75 BG,Beyaz,Sedan,Galeriden,2. El,121212,12250
9040,2020-05-06,Tofaş,Şahin,Şahin 5 vites,1992.0,Benzin/LPG,Düz Vites,1301-1600 cc,76-100 BG,Bej,Sedan,Sahibinden,2. El,54000,16300
9041,2020-05-06,Tofaş,Doğan,SLX,1993.0,Benzin/LPG,Düz Vites,1301-1600 cc,76-100 BG,Yeşil,Sedan,Sahibinden,2. El,135000,19000
9042,2020-04-06,Tofaş,Kartal,Kartal 5 Vites,1991.0,Benzin/LPG,Düz Vites,1601-1800 cc,76-100 BG,Kırmızı,Hatchback 5 Kapı,Galeriden,2. El,250000,11000
9043,2020-04-06,Tofaş,Kartal,Kartal 5 Vites,1996.0,Benzin/LPG,Düz Vites,1301-1600 cc,51-75 BG,Beyaz,Sedan,Galeriden,2. El,11,15750

In [16]:
car["Model Yıl"]=pd.to_numeric(car["Model Yıl"],downcast="integer") 
car

,İlan Tarihi,Marka,Arac Tip Grubu,Arac Tip,Model Yıl,Yakıt Turu,Vites,CCM,Beygir Gucu,Renk,Kasa Tipi,Kimden,Durum,Km,Fiyat
0,2020-05-27,Jaguar,XF,2.0 D Prestige Plus,2017,Dizel,Otomatik Vites,1801-2000 cc,176-200 BG,Lacivert,Hatchback 5 Kapı,Galeriden,2. El,26100,634500
1,2020-06-16,Acura,CL,-,2015,Dizel,Yarı Otomatik Vites,1301-1600 cc,101-125 BG,Mavi,Sedan,Sahibinden,2. El,127000,151500
2,2020-06-14,Acura,CL,2.2,1994,Benzin/LPG,Düz Vites,1301-1600 cc,101-125 BG,Turkuaz,Sedan,Sahibinden,2. El,175000,19750
3,2020-11-06,Acura,CL,-,2013,Dizel,Düz Vites,1301-1600 cc,76-100 BG,Kahverengi,Sedan,Sahibinden,2. El,325,52000
4,2020-11-06,Acura,CL,2.2,2010,Dizel,Otomatik Vites,1801-2000 cc,151-175 BG,Beyaz,Sedan,Sahibinden,2. El,207000,148750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9039,2020-06-06,Tofaş,Şahin,1.6,1994,Benzin/LPG,Düz Vites,1301-1600 cc,51-75 BG,Beyaz,Sedan,Galeriden,2. El,121212,12250
9040,2020-05-06,Tofaş,Şahin,Şahin 5 vites,1992,Benzin/LPG,Düz Vites,1301-1600 cc,76-100 BG,Bej,Sedan,Sahibinden,2. El,54000,16300
9041,2020-05-06,Tofaş,Doğan,SLX,1993,Benzin/LPG,Düz Vites,1301-1600 cc,76-100 BG,Yeşil,Sedan,Sahibinden,2. El,135000,19000
9042,2020-04-06,Tofaş,Kartal,Kartal 5 Vites,1991,Benzin/LPG,Düz Vites,1601-1800 cc,76-100 BG,Kırmızı,Hatchback 5 Kapı,Galeriden,2. El,250000,11000
9043,2020-04-06,Tofaş,Kartal,Kartal 5 Vites,1996,Benzin/LPG,Düz Vites,1301-1600 cc,51-75 BG,Beyaz,Sedan,Galeriden,2. El,11,15750

In [17]:
car["Model Yıl"].astype("int64")

0       2017
1       2015
2       1994
3       2013
4       2010
        ...
9039    1994
9040    1992
9041    1993
9042    1991
9043    1996
Name: Model Yıl, Length: 9044, dtype: int64

In [18]:
car.groupby("Marka").mean()

              Model Yıl             Km          Fiyat
Marka
Acura       2012.976190  101243.904762  123534.523810
Alfa Romeo  2010.117647  159852.235294  110961.764706
Audi        2012.823256  139425.425581  259749.369767
BMW         2012.082792  140001.512987  294943.738636
Chery       2010.000000  127000.000000   25500.000000
Chevrolet   2009.409449  162680.236220   99175.188976
Chrysler    2003.923077  236846.153846   94126.923077
Citroen     2012.618090  139889.396985   79485.165829
Dacia       2015.040248  140804.662539   81834.671827
Fiat        2011.365443  134623.822630   68076.585627
Ford        2011.553156  141907.818937   94689.591362
Geely       2011.500000    7094.000000   43250.000000
Honda       2008.726236  131830.026616  106489.064639
Hyundai     2012.020344  133572.968701   98060.931142
Infiniti    2008.200000  150347.200000  228390.000000
Isuzu       2014.222222  116288.888889  119788.888889
Jaguar      2015.466667   48296.233333  531438.333333
Jeep        2005.692308  154677.813187  198877.362637
Kia         2012.765060  117613.638554  117616.849398
Lada        1999.562500  146690.812500   22143.750000
Land Rover  2012.307692  149923.148352  594363.736264
Maserati    2011.333333   93333.333333  526740.666667
Mazda       2002.750000  208949.875000   64183.333333
Mercedes    2010.066884  144557.283850  316946.249592
Mini        2012.322581   94918.193548  150258.064516
Mitsubishi  2008.093750  205241.531250   77779.687500
Nissan      2012.877729  107551.161572  131742.655022
Opel        2010.078825  142664.160742   88531.829985
Peugeot     2012.819477  119466.817102  107926.505938
Porsche     2014.196429   92411.910714  966249.821429
Renault     2012.884079  136133.928812   85985.257335
Rover       1999.500000  162819.500000   34125.000000
Seat        2013.662252  112805.423841  120630.112583
Skoda       2012.521236  129029.467181  128163.498069
Tofaş       1994.155556  104362.711111   17234.444444
Volkswagen  2017.000000  142000.000000  123500.000000

In [19]:
car.groupby(["Marka","Arac Tip Grubu"]).mean()

                             Model Yıl             Km          Fiyat
Marka      Arac Tip Grubu
Acura      CL              2009.384615  146065.769231   92688.461538
           RSX             2019.000000   18835.600000  179103.333333
           TL              2016.000000  172000.000000   92000.000000
Alfa Romeo 145             2015.000000  104860.000000  343250.000000
           147             2006.000000  236625.000000   52562.500000
...                                ...            ...            ...
Tofaş      Doğan           1992.800000  134346.333333   17863.333333
           Kartal          1994.500000   69522.375000   16212.500000
           Serçe           1991.500000   99500.000000   14950.000000
           Şahin           1995.300000   96297.400000   17400.000000
Volkswagen Polo            2017.000000  142000.000000  123500.000000

[405 rows x 3 columns]

In [20]:
car.groupby(["Marka","Arac Tip Grubu","Yakıt Turu"]).mean()

                                      Model Yıl             Km          Fiyat
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin        2016.00   70000.000000   77500.000000
                          Benzin/LPG    2001.40  171000.000000   39200.000000
                          Dizel         2011.05  143635.500000  106820.000000
           RSX            Hibrit        2019.00   18835.600000  179103.333333
           TL             Dizel         2016.00  172000.000000   92000.000000
...                                         ...            ...            ...
Tofaş      Serçe          Benzin/LPG    1991.50   99500.000000   14950.000000
           Şahin          Benzin        1992.00   81500.000000   20250.000000
                          Benzin/LPG    1995.50  102413.777778   17500.000000
                          Dizel         1995.00    1000.000000   12750.000000
Volkswagen Polo           Dizel         2017.00  142000.000000  123500.000000

[701 rows x 3 columns]

In [21]:
car.groupby(["Marka","Arac Tip Grubu","Yakıt Turu"]).first()

                                     İlan Tarihi             Arac Tip  \
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin      2020-04-14                  2.2
                          Benzin/LPG  2020-06-14                  2.2
                          Dizel       2020-06-16                    -
           RSX            Hibrit      2020-05-29               Type-S
           TL             Dizel       2020-03-21                Diğer
...                                          ...                  ...
Tofaş      Serçe          Benzin/LPG  2020-06-15                Serçe
           Şahin          Benzin      2020-06-15        Şahin 5 vites
                          Benzin/LPG  2020-06-15                    S
                          Dizel       2020-06-14                  1.6
Volkswagen Polo           Dizel       2020-06-13  1.4 TDI Comfortline

                                      Model Yıl                Vites  \
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin           2016            Düz Vites
                          Benzin/LPG       1994            Düz Vites
                          Dizel            2015  Yarı Otomatik Vites
           RSX            Hibrit           2019       Otomatik Vites
           TL             Dizel            2016            Düz Vites
...                                         ...                  ...
Tofaş      Serçe          Benzin/LPG       1993            Düz Vites
           Şahin          Benzin           1992            Düz Vites
                          Benzin/LPG       1998            Düz Vites
                          Dizel            1995            Düz Vites
Volkswagen Polo           Dizel            2017       Otomatik Vites

                                                  CCM     Beygir Gucu  \
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin      1300 cc ve altı       76-100 BG
                          Benzin/LPG     1301-1600 cc      101-125 BG
                          Dizel          1301-1600 cc      101-125 BG
           RSX            Hibrit         1601-1800 cc  100 BG ve altı
           TL             Dizel            Bilmiyorum      Bilmiyorum
...                                               ...             ...
Tofaş      Serçe          Benzin/LPG  1300 cc ve altı        51-75 BG
           Şahin          Benzin         1301-1600 cc       76-100 BG
                          Benzin/LPG     1301-1600 cc       76-100 BG
                          Dizel          2001-2500 cc        51-75 BG
Volkswagen Polo           Dizel          1301-1600 cc      101-125 BG

                                          Renk         Kasa Tipi      Kimden  \
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin         Mavi   Hatchback 5 Kapı   Galeriden
                          Benzin/LPG  Turkuaz              Sedan  Sahibinden
                          Dizel          Mavi              Sedan  Sahibinden
           RSX            Hibrit        Beyaz              Sedan     Yetkili
           TL             Dizel         Beyaz              Sedan  Sahibinden
...                                        ...               ...         ...
Tofaş      Serçe          Benzin/LPG     Krem              Sedan   Galeriden
           Şahin          Benzin          Bej              Sedan   Galeriden
                          Benzin/LPG    Beyaz              Sedan   Galeriden
                          Dizel         Beyaz              Sedan   Galeriden
Volkswagen Polo           Dizel         Beyaz   Hatchback 5 Kapı   Galeriden

                                      Durum      Km   Fiyat
Marka      Arac Tip Grubu Yakıt Turu
Acura      CL             Benzin      2. El   70000   77500
                          Benzin/LPG  2. El  175000   19750
                          Dizel       2. El  127000  151500
           RSX            Hibrit       0 km   15662  189000
           TL             Dizel       2. El  172000   92000
...                                     ...     ...     ...
Tofaş      Serçe          Benzin/LPG  2. El   99000   16400
           Şahin          Benzin      2. El   81500   20250
                          Benzin/LPG  2. El     287   11250
                          Dizel       2. El    1000   12750
Volkswagen Polo           Dizel       2. El  142000  123500

[701 rows x 12 columns]